# Firebase configuration
firebase.service-account=act23mar-firebase-adminsdk.json
firebase.project-id=act23mar

# Default health values for new battles
firebase.default-health1=100
firebase.default-health2=100
